services:
  web:
    image: pruebatecnica:latest
    build:
      context: "C:\\Repositorios\\Trabajo\\Prueba Tecnica 2\\PruebaTecnica2\\Prueba Tecnica" # Ruta completa
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConexionDatabase=Server=db;Port=3306;Database=pruebatecnica;User Id=user;Password=1234; # Conexión a la base de datos
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pruebatecnica
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
